version: 2
jobs:
  build:
    working_directory: ~/channel
    docker:
      - image: circleci/clojure:lein-2.7.1
    environment:
      LEIN_ROOT: "true"
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: channel-{{ checksum "project.clj" }}
      - run: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: channel-{{ checksum "project.clj" }}
      - run: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/channel.jar
          destination: uberjar
