version: 2
jobs:
  build:
    working_directory: ~/channel
    docker:
      - image: circleci/clojure:lein-2.7.1
        environment:
          - DATABASE_URL=postgresql://localhost:5432/channel?user=channel
          - LEIN_ROOT: "true"
          - JVM_OPTS: -Xmx3200m
      - image: postgres:9.6
        environment:
          - POSTGRES_USER=channel
          - POSTGRES_DB=channel
    steps:
      - checkout
      - restore_cache:
          key: channel-{{ checksum "project.clj" }}
      - run:
          name: Install leiningen dependencies
          command: lein deps
      - save_cache:
          paths:
            - ~/.m2
          key: channel-{{ checksum "project.clj" }}
      - run:
          name: Setup DB
          command: lein migratus migrate
      - run:
          name: Run tests and build uberjar
          command: lein do test, uberjar
      - store_artifacts:
          path: target/uberjar/channel.jar
          destination: uberjar
